### ISSUE TITLE
Blocking Error

### ISSUE THREAD

**Issue by kevdevrev** [tr4wzified/KnowYourArmorPatcher#14]
Getting a blocking error on Armor and Enemy patchers

**Comment by kevdevrev** [comment]
Program.cs(266,63): error CS0019: Operator '??' cannot be applied to operands of type 'float' and 'int'
Program.cs(266,63): error CS0019: Operator '??' cannot be applied to operands of type 'float' and 'int'

**Comment by tr4wzified** [comment]
Not sure what's going on there since it works fine for me, but I changed something that may affect it anyway so see if it works now :)
