### ISSUE TITLE
Doubled descriptions

### ISSUE THREAD

**Issue by Irwine** [tr4wzified/KnowYourArmorPatcher#15]
When I use the setting Patch armor descriptions, the description are doubled in return.

**Comment by tr4wzified** [comment]
Did you already have a Synthesis.esp active or another esp with the changes forwarded? Disable that prior to rerunning this patcher

**Comment by Irwine** [comment]
Oh had an old patch in an other mod folder, wasn't thinking that's inactive plugin was the culprist.
One issue less, now the other one special characteres like (é,à,ê etc.).
Sorry for the troubles
