### ISSUE TITLE
RecordException

### ISSUE THREAD

**Issue by pentapox** [tr4wzified/KnowYourArmorPatcher#25]
RecordException  => HousecarlWindhelm (0A2C90:Skyrim.esm<Npc>): Specified argument was out of the range of valid values. (Parameter 'length') System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')

This occurs, not sure what's causing it. Never happened before.

**Comment by pentapox** [comment]
Got it, it was caused by Purist's Vanilla Patch.

**Comment by tr4wzified** [comment]
Ah, was about to ask which plugins were overriding that record. Glad you got it :)
